import Layout from "./model/ClassLayoutModel.js";

const roomLayoutData = [
    // Data for Teacher 1
     {block_name: 'V', floor: 1, room_number: '101' },
    { block_name: 'V', floor: 1, room_number: '103' },
    {block_name: 'V', floor: 1, room_number: '104' },
    { block_name: 'V', floor: 1, room_number: '105'},
    { block_name: 'V', floor: 1, room_number: '106'},
    { block_name: 'V', floor: 1, room_number: '107'},
    { block_name: 'V', floor: 1, room_number: '108'},
    { block_name: 'V', floor: 1, room_number: '109'},
    { block_name: 'V', floor: 1, room_number: '110'},
    { block_name: 'V', floor: 2, room_number: '201'},
    { block_name: 'V', floor: 2, room_number: '202'},
    { block_name: 'V', floor: 2, room_number: '203'},
    { block_name: 'V', floor: 2, room_number: '204'},
    { block_name: 'V', floor: 2, room_number: '205'},
    { block_name: 'V', floor: 2, room_number: '206'},
    { block_name: 'V', floor: 2, room_number: '207'},
    { block_name: 'V', floor: 2, room_number: '208'},
    { block_name: 'V', floor: 2, room_number: '209'},
    { block_name: 'V', floor: 2, room_number: '210'},
    { block_name: 'V', floor: 3, room_number: '301'},
    { block_name: 'V', floor: 3, room_number: '302'},
    { block_name: 'V', floor: 3, room_number: '303'},
    { block_name: 'V', floor: 3, room_number: '304'},
    { block_name: 'V', floor: 3, room_number: '305'},
    { block_name: 'V', floor: 3, room_number: '306'},
    { block_name: 'V', floor: 3, room_number: '307'},
    { block_name: 'V', floor: 3, room_number: '308'},
    { block_name: 'V', floor: 3, room_number: '309'},
    { block_name: 'V', floor: 3, room_number: '310'},
    { block_name: 'V', floor: 4, room_number: '401'},
    { block_name: 'V', floor: 4, room_number: '402'},
    { block_name: 'V', floor: 4, room_number: '403'},
    { block_name: 'V', floor: 4, room_number: '404'},
    { block_name: 'V', floor: 4, room_number: '405'},
    { block_name: 'V', floor: 4, room_number: '406'},
    { block_name: 'V', floor: 4, room_number: '407'},
    { block_name: 'V', floor: 4, room_number: '408'},
    { block_name: 'V', floor: 4, room_number: '409'},
    { block_name: 'V', floor: 4, room_number: '410'},
    { block_name: 'V', floor: 5, room_number: '501'},
    { block_name: 'V', floor: 5, room_number: '502'},
    { block_name: 'V', floor: 5, room_number: '503'},
    { block_name: 'V', floor: 5, room_number: '504'},
    { block_name: 'V', floor: 5, room_number: '505'},
    { block_name: 'V', floor: 5, room_number: '506'},
    { block_name: 'V', floor: 5, room_number: '507'},
    { block_name: 'V', floor: 5, room_number: '508'},
    { block_name: 'V', floor: 5, room_number: '509'},
    { block_name: 'V', floor: 5, room_number: '510'},
    
    // Data for Teacher 2
    {block_name: 'SR', floor: 1, room_number: '101' },
    {block_name: 'SR', floor: 1, room_number: '102' },
    {block_name: 'SR', floor: 1, room_number: '103' },
    {block_name: 'SR', floor: 1, room_number: '104' },
    {block_name: 'SR', floor: 1, room_number: '105' },
    {block_name: 'SR', floor: 1, room_number: '106' },
    {block_name: 'SR', floor: 1, room_number: '107' },
    {block_name: 'SR', floor: 1, room_number: '108' },
    {block_name: 'SR', floor: 1, room_number: '109' },
    {block_name: 'SR', floor: 1, room_number: '110' },
    {block_name: 'SR', floor: 2, room_number: '201' },
    {block_name: 'SR', floor: 2, room_number: '202' },
    {block_name: 'SR', floor: 2, room_number: '203' },
    {block_name: 'SR', floor: 2, room_number: '204' },
    {block_name: 'SR', floor: 2, room_number: '205' },
    {block_name: 'SR', floor: 2, room_number: '206' },
    {block_name: 'SR', floor: 2, room_number: '207' },
    {block_name: 'SR', floor: 2, room_number: '208' },
    {block_name: 'SR', floor: 2, room_number: '209' },
    {block_name: 'SR', floor: 2, room_number: '210' },
    {block_name: 'SR', floor: 3, room_number: '301' },
    {block_name: 'SR', floor: 3, room_number: '302' },
    {block_name: 'SR', floor: 3, room_number: '303' },
    {block_name: 'SR', floor: 3, room_number: '304' },
    {block_name: 'SR', floor: 3, room_number: '305' },
    {block_name: 'SR', floor: 3, room_number: '306' },
    {block_name: 'SR', floor: 3, room_number: '307' },
    {block_name: 'SR', floor: 3, room_number: '308' },
    {block_name: 'SR', floor: 3, room_number: '309' },
    {block_name: 'SR', floor: 3, room_number: '310' },
    {block_name: 'SR', floor: 4, room_number: '401' },
    {block_name: 'SR', floor: 4, room_number: '402' },
    {block_name: 'SR', floor: 4, room_number: '403' },
    {block_name: 'SR', floor: 4, room_number: '404' },
    {block_name: 'SR', floor: 4, room_number: '405' },
    {block_name: 'SR', floor: 4, room_number: '406' },
    {block_name: 'SR', floor: 4, room_number: '407' },
    {block_name: 'SR', floor: 4, room_number: '408' },
    {block_name: 'SR', floor: 4, room_number: '409' },
    {block_name: 'SR', floor: 4, room_number: '410' },
    {block_name: 'SR', floor: 5, room_number: '501' },
    {block_name: 'SR', floor: 5, room_number: '502' },
    {block_name: 'SR', floor: 5, room_number: '503' },
    {block_name: 'SR', floor: 5, room_number: '504' },
    {block_name: 'SR', floor: 5, room_number: '505' },
    {block_name: 'SR', floor: 5, room_number: '506' },
    {block_name: 'SR', floor: 5, room_number: '507' },
    {block_name: 'SR', floor: 5, room_number: '508' },
    {block_name: 'SR', floor: 5, room_number: '509' },
    {block_name: 'SR', floor: 5, room_number: '510' },
    {block_name: 'CV', floor: 1, room_number: '101' },
    {block_name: 'CV', floor: 1, room_number: '102' },
    {block_name: 'CV', floor: 1, room_number: '103' },
    {block_name: 'CV', floor: 1, room_number: '104' },
    {block_name: 'CV', floor: 1, room_number: '105' },
    {block_name: 'CV', floor: 1, room_number: '106' },
    {block_name: 'CV', floor: 1, room_number: '107' },
    {block_name: 'CV', floor: 1, room_number: '108' },
    {block_name: 'CV', floor: 1, room_number: '109' },
    {block_name: 'CV', floor: 1, room_number: '110' },
    {block_name: 'CV', floor: 2, room_number: '201' },
    {block_name: 'CV', floor: 2, room_number: '202' },
    {block_name: 'CV', floor: 2, room_number: '203' },
    {block_name: 'CV', floor: 2, room_number: '204' },
    {block_name: 'CV', floor: 2, room_number: '205' },
    {block_name: 'CV', floor: 2, room_number: '206' },
    {block_name: 'CV', floor: 2, room_number: '207' },
    {block_name: 'CV', floor: 2, room_number: '208' },
    {block_name: 'CV', floor: 2, room_number: '209' },
    {block_name: 'CV', floor: 2, room_number: '210' },
    {block_name: 'CV', floor: 3, room_number: '301' },
    {block_name: 'CV', floor: 3, room_number: '302' },
    {block_name: 'CV', floor: 3, room_number: '303' },
    {block_name: 'CV', floor: 3, room_number: '304' },
    {block_name: 'CV', floor: 3, room_number: '305' },
    {block_name: 'CV', floor: 3, room_number: '306' },
    {block_name: 'CV', floor: 3, room_number: '307' },
    {block_name: 'CV', floor: 3, room_number: '308' },
    {block_name: 'CV', floor: 3, room_number: '309' },
    {block_name: 'CV', floor: 3, room_number: '310' },
    {block_name: 'CV', floor: 4, room_number: '401' },
    {block_name: 'CV', floor: 4, room_number: '402' },
    {block_name: 'CV', floor: 4, room_number: '403' },
    {block_name: 'CV', floor: 4, room_number: '404' },
    {block_name: 'CV', floor: 4, room_number: '405' },
    {block_name: 'CV', floor: 4, room_number: '406' },
    {block_name: 'CV', floor: 4, room_number: '407' },
    {block_name: 'CV', floor: 4, room_number: '408' },
    {block_name: 'CV', floor: 4, room_number: '409' },
    {block_name: 'CV', floor: 4, room_number: '410' },
    {block_name: 'CV', floor: 5, room_number: '501' },
    {block_name: 'CV', floor: 5, room_number: '502' },
    {block_name: 'CV', floor: 5, room_number: '503' },
    {block_name: 'CV', floor: 5, room_number: '504' },
    {block_name: 'CV', floor: 5, room_number: '505' },
    {block_name: 'CV', floor: 5, room_number: '506' },
    {block_name: 'CV', floor: 5, room_number: '507' },
    {block_name: 'CV', floor: 5, room_number: '508' },
    {block_name: 'CV', floor: 5, room_number: '509' },
    {block_name: 'CV', floor: 5, room_number: '510' },
    
];

function addRoom() {
Layout.insertMany(roomLayoutData)
    .then(() => {
        console.log('Timetable data inserted successfully!');
        mongoose.connection.close();
    })
    .catch(err => {
        console.log(err);
        mongoose.connection.close();
    });

}

export default addRoom